### ISSUE TITLE
Enable Performance Insights

### ISSUE THREAD

**Issue by sumodirjo** [traveloka/terraform-aws-rds-postgres#13]
## Background
Performance Insight is supported for RDS postgres version 10. We need to provide support to enable performance insight for RDS postgres version 10 and 11.

Enabling performance insight will enable database owner to get better visibility of their RDS postgres instance condition.

## References

* https://aws.amazon.com/about-aws/whats-new/2018/04/rds-performance-insights-on-rds-for-postgresql/

**Comment by rafikurnia** [comment]
Hi @sumodirjo , can you please provide a hint of what should be changed on the module? It would be nice if you could help to submit a PR though :wink:
