### ISSUE TITLE
Enabling CA Certificate Identifier to be configurable

### ISSUE THREAD

**Issue by nazmy** [traveloka/terraform-aws-rds-postgres#20]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description
On Nov 2019, Terraform enables ca_cert_identifier to be configurable. Enabling ca_cert_identifier to be configurable in terraform will ease the database owner to update the ca_cert_identifier.

### New or Affected Resource(s)

* aws_db_instance

### Potential Terraform Configuration Changes

locals.tf:
```hcl
ca_cert_identifier = "rds-ca-2019"
```
main.tf:
```hcl
rds_ca_cert_identifier    = "${local.ca_cert_identifier}"
```

### References

https://www.terraform.io/docs/providers/aws/r/db_instance.html#ca_cert_identifier

**Comment by nazmy** [comment]
@rafikurnia, I've created a PR to solve this issue https://github.com/traveloka/terraform-aws-rds-postgres/pull/21

**Comment by sshvetsov** [comment]
@nazmy could you provide proper description of this issue in the ticket?

**Comment by nazmy** [comment]
@sshvetsov, Sorry I forgot to remove the commented "<!---" code. I've updated the description accordingly.

cc @rafikurnia

**Comment by sshvetsov** [comment]
Those are not "unnecessary" comments, those are sections you are expected to fill out.

**Comment by nazmy** [comment]
@sshvetsov, is the revised descriptions ok?

**Comment by sshvetsov** [comment]
@nazmy Better, I've added the resource for you, but it would help to have a sample of TF code showing how you propose to use the proposed feature. As these modules are used by many teams, Issues provide a record as to why they are being implemented or declined.

**Comment by steve-ng** [comment]
hi @sshvetsov, added in examples.tf as suggested. `ca_cert_identifier` is optional now with the test cases explained in the PR as well. Would @traveloka/techops be able to assist in the review?
