### ISSUE TITLE
Add variable to set additional tags

### ISSUE THREAD

**Issue by davidasync** [traveloka/terraform-aws-rds-postgres#28]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description
Tags at rds sometimes are needed to filter metrics at third party monitoring such as datadog

### New or Affected Resource(s)
aws_db_instance

### Potential Terraform Configuration Changes
```
tags = "${merge(map(
    "Name", random_id.db_identifier.hex,
    "Service", var.service_name,
    "ProductDomain", var.product_domain,
    "Environment", var.environment,
    "Description", var.description,
    "ManagedBy", "Terraform",
    ), var.additional_tags)}"
```

### References

* #0000

**Comment by sshvetsov** [comment]
The tag "ManagedBy" should have lowercase value "terraform"
